/* Autogenerated by png2wx.pl on Tue Oct 13 10:17:26 2015 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ccw;
extern wxBitmap *_img_courseup;
extern wxBitmap *_img_cw;
extern wxBitmap *_img_headingup;
extern wxBitmap *_img_northup;
extern wxBitmap *_img_rotation;
extern wxBitmap *_img_routeup;
extern wxBitmap *_img_southup;
extern wxBitmap *_img_tiltdown;
extern wxBitmap *_img_tiltup;
extern wxBitmap *_img_t;
extern wxBitmap *_img_windup;

#endif /* ICONS_H */
