/* Autogenerated by png2wx.pl on Mon Jan 12 00:15:13 2015 */
#ifndef ___SRC_ICONS_H
#define ___SRC_ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_ccw;
extern wxBitmap *_img_courseup;
extern wxBitmap *_img_cw;
extern wxBitmap *_img_headingup;
extern wxBitmap *_img_northup;
extern wxBitmap *_img_rotation;
extern wxBitmap *_img_routeup;
extern wxBitmap *_img_southup;
extern wxBitmap *_img_windup;

#endif /* ___SRC_ICONS_H */
